# Generated by Django 5.2.7 on 2025-10-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageurl', models.TextField(blank=True, null=True)),
                ('preview', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('infourl', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ln_books',
                'managed': False,
            },
        ),
    ]
